name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testAttackWhenVisible
      id: testattackwhenvisible
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testAttackWhenVisible
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "InvisibleHeroTest.testAttackWhenVisible"
        timeout: 10
        max-score: 3
    - name: testAttackWhenInvisible
      id: testattackwheninvisible
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testAttackWhenInvisible
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "InvisibleHeroTest.testAttackWhenInvisible"
        timeout: 10
        max-score: 3
    - name: testExtendHero
      id: testextendhero
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testExtendHero
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "InvisibleHeroTest.testExtendHero"
        timeout: 10
        max-score: 3
    - name: testMain
      id: testmain
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testMain
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog92Test.testHelloWorld"
        timeout: 10
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTATTACKWHENVISIBLE_RESULTS: "${{steps.testattackwhenvisible.outputs.result}}"
        TESTATTACKWHENINVISIBLE_RESULTS: "${{steps.testattackwheninvisible.outputs.result}}"
        TESTEXTENDHERO_RESULTS: "${{steps.testextendhero.outputs.result}}"
        TESTMAIN_RESULTS: "${{steps.testmain.outputs.result}}"
      with:
        runners: testattackwhenvisible,testattackwheninvisible,testextendhero,testmain
